name: Run Tests
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
jobs:
  maven-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Check versions
        run: |
          java -version
          javac -version
          ./mvnw -version

      - name: Test with Maven
        run: ./mvnw -B verify --file pom.xml

      - name: Build Linux DEB Package for Release
        if: ${{ startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux' }}
        run: ./scripts/package-linux-deb.sh

      - name: Build Windows MSI Package for Release
        if: ${{ startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows' }}
        run: powershell.exe -File scripts\package-windows-msi.ps1

      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            *.deb
            *.msi
