name: Run Tests
on:
  push:
    branches:
      - "*"
jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Test with Maven
        run: mvn -B verify --file pom.xml
