name: Run Tests
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Install Maven 3.9.6
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvf apache-maven-3.9.6-bin.tar.gz
          sudo mv apache-maven-3.9.6 /usr/local/apache-maven
          rm apache-maven-3.9.6-bin.tar.gz
          sudo update-alternatives --install /usr/bin/mvn mvn /usr/local/apache-maven/bin/mvn 1

      - name: Check versions
        run: |
          java -version
          javac -version
          mvn -version

      - name: Test with Maven
        run: mvn -B verify --file pom.xml

      - name: Build Package for Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./scripts/package-linux-deb.sh

      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            *.deb
